Description: Lambda and API Gateway
Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: Tuna Boys For Life

  LambdaPermission:
    DependsOn: RestApi
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: FetchUsersCLOUDFORM
      Principal: apigateway.amazonaws.com
      SourceArn: !Join ["", ["arn:aws:execute-api:", Ref: "AWS::Region", ":", Ref: "AWS::AccountId", ":", !Ref RestApi, "/*"]]

  UsersResource:
    Type: "AWS::ApiGateway::Resource"
    Properties:
      RestApiId:
        Ref: "RestApi"
      ParentId:
        Fn::GetAtt:
          - "RestApi"
          - "RootResourceId"
      PathPart: "users"

  UsersGET:
    Type: AWS::ApiGateway::Method
    DependsOn:
      - UsersResource
      - LambdaPermission
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref UsersResource
      HttpMethod: GET
      AuthorizationType: NONE
      MethodResponses:
        - StatusCode: 200
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Join ["", ["arn:aws:apigateway", Ref: "AWS::Region", ":", "lambda:path/2015-03-31/functions/arn:aws:lambda", ":", Ref: "AWS::Region", ":", Ref: "AWS::AcountId", ":function:", "FetchUsersCLOUDFORM" , "/invocations"]
        # Uri:  arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:584967964008:function:FetchUsersCLOUDFORM/invocations
        IntegrationResponses:
          - StatusCode: 200
